version: '3'
services:
  weather_data_service:
    build: ./weather_data_service
    ports:
      - "8000:8000"
  data_storage_service:
    image: mongo
    ports:
      - "27017:27017"
  web_server_service:
    build: ./web_server_service
    ports:
      - "5000:5000"
    links:
      - data_storage_service:data_storage_service
      - weather_data_service:weather_data_service
